CREATE TABLE users (id TEXT PRIMARY KEY, name TEXT NOT NULL, username TEXT NOT NULL UNIQUE COLLATE NOCASE, password_hash TEXT NOT NULL, failed_attempts INTEGER NOT NULL DEFAULT 0, locked_until INTEGER NOT NULL DEFAULT 0, archived_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE roles (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE permissions (id TEXT PRIMARY KEY);
CREATE TABLE role_permissions (role_id TEXT NOT NULL REFERENCES roles(id), permission_id TEXT NOT NULL REFERENCES permissions(id), PRIMARY KEY(role_id,permission_id));
CREATE TABLE user_roles (user_id TEXT NOT NULL REFERENCES users(id), role_id TEXT NOT NULL REFERENCES roles(id), PRIMARY KEY(user_id,role_id));
CREATE TABLE customers (id TEXT PRIMARY KEY, customer_code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', secondary_phone TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', address TEXT NOT NULL DEFAULT '', city TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', date_of_birth TEXT, gender TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, archived_at TEXT, legacy_id TEXT);
CREATE INDEX customers_name ON customers(name COLLATE NOCASE);
CREATE INDEX customers_phone ON customers(phone);
CREATE TABLE prescriptions (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL REFERENCES customers(id), exam_date TEXT, data TEXT NOT NULL CHECK(json_valid(data)), created_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL, legacy_id TEXT);
CREATE INDEX prescriptions_customer_date ON prescriptions(customer_id,exam_date);
CREATE TABLE product_types (id TEXT PRIMARY KEY);
INSERT INTO product_types VALUES ('frames'),('sunglasses'),('lenses'),('contact_lenses'),('accessories'),('other');
CREATE TABLE categories (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, type TEXT NOT NULL REFERENCES product_types(id), reorder_level INTEGER CHECK(reorder_level>=0), created_at TEXT NOT NULL, archived_at TEXT);
CREATE TABLE brands (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE suppliers (id TEXT PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', address TEXT NOT NULL DEFAULT '', tax_number TEXT NOT NULL DEFAULT '', contact_person TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, archived_at TEXT);
CREATE TABLE products (id TEXT PRIMARY KEY, name TEXT NOT NULL, sku TEXT NOT NULL UNIQUE, barcode TEXT, type TEXT NOT NULL REFERENCES product_types(id), category_id TEXT REFERENCES categories(id), brand TEXT NOT NULL DEFAULT '', model_code TEXT NOT NULL DEFAULT '', material TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '', size TEXT NOT NULL DEFAULT '', supplier_id TEXT REFERENCES suppliers(id), unit_cost INTEGER NOT NULL CHECK(unit_cost>=0), unit_price INTEGER NOT NULL CHECK(unit_price>=0), stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK(stock_quantity>=0), reorder_level INTEGER CHECK(reorder_level>=0), notes TEXT NOT NULL DEFAULT '', variants TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, archived_at TEXT, legacy_id TEXT);
CREATE UNIQUE INDEX products_barcode ON products(barcode) WHERE barcode IS NOT NULL AND barcode<>'';
CREATE INDEX products_type_category ON products(type,category_id);
CREATE INDEX products_supplier ON products(supplier_id);
CREATE TABLE sales (id TEXT PRIMARY KEY, request_id TEXT NOT NULL UNIQUE, invoice_number TEXT NOT NULL UNIQUE, customer_id TEXT REFERENCES customers(id), prescription_id TEXT REFERENCES prescriptions(id), customer_snapshot TEXT NOT NULL, prescription_snapshot TEXT, seller_id TEXT NOT NULL REFERENCES users(id), subtotal INTEGER NOT NULL CHECK(subtotal>=0), discount INTEGER NOT NULL CHECK(discount>=0 AND discount<=subtotal), tax INTEGER NOT NULL CHECK(tax>=0), total INTEGER NOT NULL CHECK(total=subtotal-discount+tax AND total>=0), notes TEXT NOT NULL, created_at TEXT NOT NULL, legacy_id TEXT);
CREATE INDEX sales_date ON sales(created_at);
CREATE INDEX sales_customer ON sales(customer_id,created_at);
CREATE TABLE sale_items (id TEXT PRIMARY KEY, sale_id TEXT NOT NULL REFERENCES sales(id), product_id TEXT NOT NULL REFERENCES products(id), product_name TEXT NOT NULL, product_type TEXT NOT NULL, brand TEXT NOT NULL, model_code TEXT NOT NULL, barcode TEXT, category_name TEXT NOT NULL, unit_price INTEGER NOT NULL CHECK(unit_price>=0), unit_cost INTEGER NOT NULL CHECK(unit_cost>=0), quantity INTEGER NOT NULL CHECK(quantity>0), subtotal INTEGER NOT NULL CHECK(subtotal=quantity*unit_price), net_total INTEGER NOT NULL CHECK(net_total>=0), notes TEXT NOT NULL);
CREATE INDEX sale_items_sale ON sale_items(sale_id);
CREATE TABLE payments (id TEXT PRIMARY KEY, sale_id TEXT NOT NULL REFERENCES sales(id), amount INTEGER NOT NULL CHECK(amount<>0), method TEXT NOT NULL, notes TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), reversal_of TEXT UNIQUE REFERENCES payments(id), created_at TEXT NOT NULL);
CREATE INDEX payments_sale_date ON payments(sale_id,created_at);
CREATE INDEX payments_date ON payments(created_at);
CREATE TABLE cash_sessions (id TEXT PRIMARY KEY, opened_by TEXT NOT NULL REFERENCES users(id), opening_balance INTEGER NOT NULL CHECK(opening_balance>=0), opened_at TEXT NOT NULL, closed_by TEXT REFERENCES users(id), closed_at TEXT, expected_balance INTEGER, actual_balance INTEGER CHECK(actual_balance>=0), difference INTEGER);
CREATE UNIQUE INDEX one_open_session ON cash_sessions((1)) WHERE closed_at IS NULL;
CREATE TABLE cash_transactions (id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES cash_sessions(id), type TEXT NOT NULL, amount INTEGER NOT NULL, reference_id TEXT, reason TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE expense_categories (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE expenses (id TEXT PRIMARY KEY, category TEXT NOT NULL, amount INTEGER NOT NULL CHECK(amount>0), method TEXT NOT NULL, description TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE purchase_orders (id TEXT PRIMARY KEY, supplier_id TEXT NOT NULL REFERENCES suppliers(id), invoice_number TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','received')), total INTEGER NOT NULL CHECK(total>=0), paid INTEGER NOT NULL CHECK(paid>=0 AND paid<=total), method TEXT NOT NULL, notes TEXT NOT NULL, created_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL, received_at TEXT);
CREATE TABLE purchase_items (id TEXT PRIMARY KEY, purchase_id TEXT NOT NULL REFERENCES purchase_orders(id), product_id TEXT NOT NULL REFERENCES products(id), quantity INTEGER NOT NULL CHECK(quantity>0), unit_cost INTEGER NOT NULL CHECK(unit_cost>=0));
CREATE TABLE returns (id TEXT PRIMARY KEY, sale_id TEXT NOT NULL REFERENCES sales(id), reason TEXT NOT NULL, total INTEGER NOT NULL CHECK(total>=0), user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE return_items (id TEXT PRIMARY KEY, return_id TEXT NOT NULL REFERENCES returns(id), sale_item_id TEXT NOT NULL REFERENCES sale_items(id), quantity INTEGER NOT NULL CHECK(quantity>0), amount INTEGER NOT NULL CHECK(amount>=0), restock INTEGER NOT NULL CHECK(restock IN (0,1)));
CREATE TABLE refunds (id TEXT PRIMARY KEY, return_id TEXT NOT NULL REFERENCES returns(id), sale_id TEXT NOT NULL REFERENCES sales(id), amount INTEGER NOT NULL CHECK(amount>0), method TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE inventory_movements (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), type TEXT NOT NULL, quantity_change INTEGER NOT NULL CHECK(quantity_change<>0), quantity_before INTEGER NOT NULL CHECK(quantity_before>=0), quantity_after INTEGER NOT NULL CHECK(quantity_after>=0 AND quantity_after=quantity_before+quantity_change), reference_type TEXT NOT NULL, reference_id TEXT NOT NULL, reason TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE INDEX inventory_product_date ON inventory_movements(product_id,created_at);
CREATE TABLE app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL CHECK(json_valid(value)));
CREATE TABLE store_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE print_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE attachments (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, file_name TEXT NOT NULL, managed_name TEXT NOT NULL UNIQUE, mime_type TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), action TEXT NOT NULL, entity TEXT NOT NULL, entity_id TEXT NOT NULL, before_data TEXT, after_data TEXT, created_at TEXT NOT NULL);
CREATE INDEX audit_date ON audit_logs(created_at);
CREATE TABLE backup_history (id TEXT PRIMARY KEY, file_name TEXT NOT NULL, checksum TEXT NOT NULL, created_at TEXT NOT NULL, user_id TEXT REFERENCES users(id));
CREATE TABLE import_history (fingerprint TEXT PRIMARY KEY, report TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit_logs BEGIN SELECT RAISE(ABORT,'Audit records are immutable'); END;
CREATE TRIGGER audit_no_delete BEFORE DELETE ON audit_logs BEGIN SELECT RAISE(ABORT,'Audit records are immutable'); END;
CREATE TRIGGER prescription_no_update BEFORE UPDATE ON prescriptions BEGIN SELECT RAISE(ABORT,'Create a new prescription version'); END;
CREATE TRIGGER prescription_no_delete BEFORE DELETE ON prescriptions BEGIN SELECT RAISE(ABORT,'Prescriptions are historical records'); END;
