ALTER TABLE sale_items ADD COLUMN tax_amount INTEGER NOT NULL DEFAULT 0 CHECK(tax_amount>=0);
ALTER TABLE sale_items ADD COLUMN discount_amount INTEGER NOT NULL DEFAULT 0 CHECK(discount_amount>=0);
ALTER TABLE return_items ADD COLUMN tax_amount INTEGER NOT NULL DEFAULT 0 CHECK(tax_amount>=0);
CREATE TRIGGER sales_no_update BEFORE UPDATE ON sales BEGIN SELECT RAISE(ABORT,'Completed invoices are immutable'); END;
CREATE TRIGGER sales_no_delete BEFORE DELETE ON sales BEGIN SELECT RAISE(ABORT,'Completed invoices cannot be deleted'); END;
CREATE TRIGGER sale_items_no_update BEFORE UPDATE ON sale_items BEGIN SELECT RAISE(ABORT,'Sale items are immutable'); END;
CREATE TRIGGER sale_items_no_delete BEFORE DELETE ON sale_items BEGIN SELECT RAISE(ABORT,'Sale items cannot be deleted'); END;
CREATE TRIGGER payments_no_update BEFORE UPDATE ON payments BEGIN SELECT RAISE(ABORT,'Use a payment reversal'); END;
CREATE TRIGGER payments_no_delete BEFORE DELETE ON payments BEGIN SELECT RAISE(ABORT,'Use a payment reversal'); END;
CREATE TRIGGER returns_no_update BEFORE UPDATE ON returns BEGIN SELECT RAISE(ABORT,'Returns are immutable'); END;
CREATE TRIGGER returns_no_delete BEFORE DELETE ON returns BEGIN SELECT RAISE(ABORT,'Returns are immutable'); END;
CREATE TRIGGER return_items_no_update BEFORE UPDATE ON return_items BEGIN SELECT RAISE(ABORT,'Return items are immutable'); END;
CREATE TRIGGER return_items_no_delete BEFORE DELETE ON return_items BEGIN SELECT RAISE(ABORT,'Return items are immutable'); END;
CREATE TRIGGER refunds_no_update BEFORE UPDATE ON refunds BEGIN SELECT RAISE(ABORT,'Refunds are immutable'); END;
CREATE TRIGGER refunds_no_delete BEFORE DELETE ON refunds BEGIN SELECT RAISE(ABORT,'Refunds are immutable'); END;
CREATE TRIGGER movements_no_update BEFORE UPDATE ON inventory_movements BEGIN SELECT RAISE(ABORT,'Stock movements are immutable'); END;
CREATE TRIGGER movements_no_delete BEFORE DELETE ON inventory_movements BEGIN SELECT RAISE(ABORT,'Stock movements are immutable'); END;
CREATE TRIGGER cash_no_update BEFORE UPDATE ON cash_transactions BEGIN SELECT RAISE(ABORT,'Cash entries are immutable'); END;
CREATE TRIGGER cash_no_delete BEFORE DELETE ON cash_transactions BEGIN SELECT RAISE(ABORT,'Cash entries are immutable'); END;
CREATE TRIGGER expenses_no_update BEFORE UPDATE ON expenses BEGIN SELECT RAISE(ABORT,'Expenses are immutable'); END;
CREATE TRIGGER expenses_no_delete BEFORE DELETE ON expenses BEGIN SELECT RAISE(ABORT,'Expenses are immutable'); END;
