ALTER TABLE products ADD COLUMN parent_product_id TEXT REFERENCES products(id);
CREATE INDEX products_parent ON products(parent_product_id);

CREATE TABLE appointments (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customers(id),starts_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('scheduled','confirmed','completed','cancelled','no_show')),purpose TEXT NOT NULL,reminder_at TEXT,reminder_sent_at TEXT,notes TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX appointments_schedule ON appointments(starts_at,status);
CREATE TABLE lab_orders (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customers(id),sale_id TEXT REFERENCES sales(id),prescription_id TEXT REFERENCES prescriptions(id),lab_name TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('draft','sent','in_progress','ready','delivered','cancelled')),expected_at TEXT,cost INTEGER NOT NULL CHECK(cost>=0),notes TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX lab_orders_status_due ON lab_orders(status,expected_at);
CREATE TABLE repairs (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customers(id),sale_id TEXT REFERENCES sales(id),status TEXT NOT NULL CHECK(status IN ('received','diagnosing','waiting_parts','ready','delivered','cancelled')),item_description TEXT NOT NULL,issue TEXT NOT NULL,resolution TEXT NOT NULL,cost INTEGER NOT NULL CHECK(cost>=0),received_at TEXT NOT NULL,due_at TEXT,delivered_at TEXT,warranty_until TEXT,notes TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX repairs_status_due ON repairs(status,due_at);
CREATE TABLE customer_followups (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customers(id),type TEXT NOT NULL CHECK(type IN ('exam','collection','lens_replacement','other')),due_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','completed','cancelled')),notes TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,completed_at TEXT,reminder_sent_at TEXT);
CREATE INDEX followups_due ON customer_followups(status,due_at);

CREATE TABLE quotes (id TEXT PRIMARY KEY,quote_number TEXT NOT NULL UNIQUE,customer_id TEXT REFERENCES customers(id),customer_snapshot TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('draft','accepted','expired','cancelled','converted')),subtotal INTEGER NOT NULL CHECK(subtotal>=0),discount INTEGER NOT NULL CHECK(discount>=0 AND discount<=subtotal),tax INTEGER NOT NULL CHECK(tax>=0),total INTEGER NOT NULL CHECK(total=subtotal-discount+tax),deposit INTEGER NOT NULL CHECK(deposit>=0 AND deposit<=total),reserved INTEGER NOT NULL CHECK(reserved IN (0,1)),expires_at TEXT,notes TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,converted_sale_id TEXT REFERENCES sales(id));
CREATE TABLE quote_items (id TEXT PRIMARY KEY,quote_id TEXT NOT NULL REFERENCES quotes(id),product_id TEXT NOT NULL REFERENCES products(id),product_snapshot TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),unit_price INTEGER NOT NULL CHECK(unit_price>=0),subtotal INTEGER NOT NULL CHECK(subtotal=quantity*unit_price));
CREATE TABLE quote_payments (id TEXT PRIMARY KEY,quote_id TEXT NOT NULL REFERENCES quotes(id),amount INTEGER NOT NULL CHECK(amount>0),method TEXT NOT NULL,notes TEXT NOT NULL,user_id TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TRIGGER quote_payments_no_update BEFORE UPDATE ON quote_payments BEGIN SELECT RAISE(ABORT,'Quote payments are immutable'); END;
CREATE TRIGGER quote_payments_no_delete BEFORE DELETE ON quote_payments BEGIN SELECT RAISE(ABORT,'Quote payments are immutable'); END;
CREATE TABLE quote_refunds (id TEXT PRIMARY KEY,quote_id TEXT NOT NULL REFERENCES quotes(id),quote_payment_id TEXT NOT NULL UNIQUE REFERENCES quote_payments(id),amount INTEGER NOT NULL CHECK(amount>0),method TEXT NOT NULL,user_id TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TRIGGER quote_refunds_no_update BEFORE UPDATE ON quote_refunds BEGIN SELECT RAISE(ABORT,'Quote refunds are immutable'); END;
CREATE TRIGGER quote_refunds_no_delete BEFORE DELETE ON quote_refunds BEGIN SELECT RAISE(ABORT,'Quote refunds are immutable'); END;
CREATE INDEX quotes_customer_date ON quotes(customer_id,created_at);

CREATE TABLE stocktakes (id TEXT PRIMARY KEY,status TEXT NOT NULL CHECK(status IN ('counting','posted','cancelled')),notes TEXT NOT NULL,started_by TEXT NOT NULL REFERENCES users(id),started_at TEXT NOT NULL,posted_by TEXT REFERENCES users(id),posted_at TEXT);
CREATE TABLE stocktake_items (stocktake_id TEXT NOT NULL REFERENCES stocktakes(id),product_id TEXT NOT NULL REFERENCES products(id),expected_quantity INTEGER NOT NULL CHECK(expected_quantity>=0),counted_quantity INTEGER CHECK(counted_quantity>=0),PRIMARY KEY(stocktake_id,product_id));
CREATE TABLE supplier_returns (id TEXT PRIMARY KEY,purchase_id TEXT NOT NULL REFERENCES purchase_orders(id),supplier_id TEXT NOT NULL REFERENCES suppliers(id),status TEXT NOT NULL CHECK(status IN ('posted','cancelled')),total INTEGER NOT NULL CHECK(total>=0),reason TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
CREATE TABLE supplier_return_items (id TEXT PRIMARY KEY,supplier_return_id TEXT NOT NULL REFERENCES supplier_returns(id),purchase_item_id TEXT NOT NULL REFERENCES purchase_items(id),product_id TEXT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity>0),unit_cost INTEGER NOT NULL CHECK(unit_cost>=0));
CREATE INDEX supplier_returns_purchase ON supplier_returns(purchase_id,created_at);

CREATE TABLE branches (id TEXT PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,address TEXT NOT NULL,phone TEXT NOT NULL,is_active INTEGER NOT NULL CHECK(is_active IN (0,1)),created_at TEXT NOT NULL);
INSERT INTO branches VALUES ('00000000-0000-4000-8000-000000000010','MAIN','Main branch','','',1,datetime('now'));
CREATE TABLE branch_stock (branch_id TEXT NOT NULL REFERENCES branches(id),product_id TEXT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity>=0),PRIMARY KEY(branch_id,product_id));
INSERT INTO branch_stock SELECT '00000000-0000-4000-8000-000000000010',id,stock_quantity FROM products;
CREATE TABLE stock_reservations (id TEXT PRIMARY KEY,quote_id TEXT NOT NULL REFERENCES quotes(id),branch_id TEXT NOT NULL REFERENCES branches(id),product_id TEXT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity>0),status TEXT NOT NULL CHECK(status IN ('active','fulfilled','released')),expires_at TEXT,created_at TEXT NOT NULL);
CREATE INDEX stock_reservations_available ON stock_reservations(branch_id,product_id,status,expires_at);
CREATE TABLE inventory_transfers (id TEXT PRIMARY KEY,from_branch_id TEXT NOT NULL REFERENCES branches(id),to_branch_id TEXT NOT NULL REFERENCES branches(id),status TEXT NOT NULL CHECK(status IN ('posted','cancelled')),notes TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,CHECK(from_branch_id<>to_branch_id));
CREATE TABLE inventory_transfer_items (id TEXT PRIMARY KEY,transfer_id TEXT NOT NULL REFERENCES inventory_transfers(id),product_id TEXT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity>0));
CREATE TABLE sync_outbox (id TEXT PRIMARY KEY,event_type TEXT NOT NULL,entity_id TEXT NOT NULL,payload TEXT NOT NULL CHECK(json_valid(payload)),created_at TEXT NOT NULL,synced_at TEXT);
CREATE TRIGGER sync_outbox_no_update BEFORE UPDATE ON sync_outbox WHEN OLD.synced_at IS NOT NULL BEGIN SELECT RAISE(ABORT,'Synced outbox events are immutable'); END;
CREATE TRIGGER sync_outbox_no_delete BEFORE DELETE ON sync_outbox BEGIN SELECT RAISE(ABORT,'Outbox events are immutable'); END;
ALTER TABLE sales ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE purchase_orders ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE expenses ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE inventory_movements ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE stocktakes ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE appointments ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE lab_orders ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE repairs ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE customer_followups ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE quotes ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE supplier_returns ADD COLUMN branch_id TEXT REFERENCES branches(id);
ALTER TABLE cash_sessions ADD COLUMN branch_id TEXT REFERENCES branches(id);
DROP INDEX one_open_session;
CREATE UNIQUE INDEX one_open_session_per_branch ON cash_sessions(branch_id) WHERE closed_at IS NULL;
UPDATE sales SET branch_id='00000000-0000-4000-8000-000000000010';
UPDATE purchase_orders SET branch_id='00000000-0000-4000-8000-000000000010';
UPDATE expenses SET branch_id='00000000-0000-4000-8000-000000000010';
UPDATE inventory_movements SET branch_id='00000000-0000-4000-8000-000000000010';
UPDATE supplier_returns SET branch_id=(SELECT branch_id FROM purchase_orders WHERE id=supplier_returns.purchase_id);
UPDATE cash_sessions SET branch_id='00000000-0000-4000-8000-000000000010';
