import { useState } from 'react';
import { ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,BarChart,Bar } from 'recharts';
import { useApp,useData } from '../lib';
import { PageHeader,Money,DataTable } from '../components';
import { periods } from '../../../../packages/shared/dates';
export function DashboardPage(){const {t,can}=useApp();const [period,setPeriod]=useState('today');const [from,setFrom]=useState('');const [to,setTo]=useState('');const data=useData('dashboard.get',{period,from:from||undefined,to:to||undefined},period!=='custom'||Boolean(from&&to));const low=useData('inventory.low',undefined,can('inventory.view'));
  const labels:Record<string,[string,string]>={revenue:['Net revenue','صافي المبيعات'],cogs:['Cost of goods','تكلفة البضاعة'],profit:['Gross profit','مجمل الربح'],sales:['Sales','المبيعات'],average_order:['Average sale','متوسط الفاتورة'],collected:['Collected payments','الدفعات المحصلة'],expenses:['Expenses','المصروفات'],refunds:['Refunds','المبالغ المستردة'],cash_movement:['Cash movement','حركة النقدية'],new_customers:['New customers','عملاء جدد'],debt:['Outstanding debt','المديونية'],revenue_growth:['Revenue growth','نمو المبيعات'],profit_growth:['Profit growth','نمو الربح']};
  return <><PageHeader title={t('Shop overview','نظرة عامة على المحل')} subtitle={t('Your sales, collections and stock at a glance','المبيعات والتحصيل والمخزون في مكان واحد')}><button onClick={()=>void data.refetch()}>{t('Refresh','تحديث')}</button><select value={period} onChange={e=>setPeriod(e.target.value)}>{periods.map(p=><option key={p} value={p}>{p.replaceAll('_',' ')}</option>)}</select></PageHeader>{period==='custom'&&<div className="toolbar"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div>}{data.error&&<p className="error">{data.error.message}</p>}<div className="kpi-grid">{Object.entries(data.data?.metrics??{}).map(([key,value])=><div className="kpi" key={key}><span>{t(...(labels[key]??[key,key]))}</span><strong>{value===null?'—':key.includes('growth')?`${value.toFixed(1)}%`:['sales','new_customers'].includes(key)?value:<Money value={value}/>}</strong></div>)}</div>
    <div className="chart-grid"><section className="panel"><h2>{t('Revenue trend','اتجاه الإيرادات')}</h2><ResponsiveContainer width="100%" height={260}><AreaChart data={data.data?.trend??[]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day"/><YAxis tickFormatter={value=>String(Number(value)/100)}/><Tooltip formatter={value=>Number(value)/100}/><Area type="monotone" dataKey="revenue" stroke="#087c83" fill="#cdeceb"/></AreaChart></ResponsiveContainer></section><section className="panel"><h2>{t('Sales by product type','المبيعات حسب النوع')}</h2><ResponsiveContainer width="100%" height={260}><BarChart data={data.data?.by_type??[]}><XAxis dataKey="name"/><YAxis tickFormatter={value=>String(Number(value)/100)}/><Tooltip formatter={value=>Number(value)/100}/><Bar dataKey="amount" fill="#087c83" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></section></div>
    {can('inventory.view')&&<section className="panel"><h2>{t('Reorder watch','متابعة إعادة الطلب')}</h2><DataTable rows={low.data??[]} columns={[{key:'name',label:t('Product','المنتج')},{key:'sku',label:'SKU'},{key:'stock_quantity',label:t('Available','المتاح')},{key:'reorder_level',label:t('Reorder level','حد إعادة الطلب')}]}/></section>}</>;
}
