import { useState } from 'react';
import { api,client,useApp,useData } from '../lib';
import { DataTable,Modal,Money,RecordForm } from '../components';
import { PrescriptionView } from '../../../../packages/ui/PrescriptionView';
import { methods,type Prescription } from '../../../../packages/shared/schemas';
import { minor } from '../../../../packages/shared/money';
export function InvoiceDetail({saleId,onClose}:{saleId:string;onClose:()=>void}){
  const {t,settings,can,run}=useApp();const data=useData('sales.get',saleId);const [payment,setPayment]=useState(false);const [returnLine,setReturnLine]=useState<string|null>(null);const invoice=data.data;
  return <Modal title={String(invoice?.sale.invoice_number??t('Invoice','الفاتورة'))} onClose={onClose}>{data.error&&<p className="error">{data.error.message}</p>}{invoice&&<><div className="section-heading"><div><h3>{JSON.parse(String(invoice.sale.customer_snapshot)).name}</h3><p>{invoice.sale.created_at}</p></div><div className="actions"><button onClick={()=>run(()=>api('print.preview',{kind:'invoice',id:saleId}))}>{t('Invoice preview','معاينة الفاتورة')}</button><button onClick={()=>run(()=>api('print.preview',{kind:'comprehensive',id:saleId}))}>{t('Invoice + prescription','الفاتورة والوصفة')}</button><button onClick={()=>run(()=>api('print.execute'))}>{t('Print','طباعة')}</button><button onClick={()=>run(()=>api('print.pdf'))}>PDF</button></div></div>
    <DataTable rows={invoice.items} columns={[{key:'product_name',label:t('Product','المنتج')},{key:'quantity',label:t('Quantity','الكمية')},{key:'returned_quantity',label:t('Returned','المرتجع')},{key:'subtotal',label:t('Amount','المبلغ'),render:r=><Money value={r.subtotal}/>}]} actions={can('sales.return')?row=><button disabled={Number(row.returned_quantity)>=Number(row.quantity)} onClick={()=>setReturnLine(String(row.id))}>{t('Return','إرجاع')}</button>:undefined}/>
    <div className="kpi-grid small">{[['Total','الإجمالي',invoice.total],['Paid','المدفوع',invoice.paid],['Returns','المرتجعات',invoice.returned],['Refunded','المسترد',invoice.refunded],['Balance','المتبقي',invoice.balance]].map(([en,ar,value])=><div className="kpi" key={String(en)}><span>{t(String(en),String(ar))}</span><strong><Money value={value}/></strong></div>)}</div>
    {invoice.balance>0&&can('payments.create')&&<button className="primary" onClick={()=>setPayment(true)}>{t('Record payment','تسجيل دفعة')}</button>}
    {invoice.sale.prescription_snapshot&&<PrescriptionView prescription={JSON.parse(String(invoice.sale.prescription_snapshot)) as Prescription} language={settings.language}/>}
    <h3>{t('Payment history','سجل الدفعات')}</h3><DataTable rows={invoice.payments} columns={[{key:'created_at',label:t('Date','التاريخ')},{key:'method',label:t('Method','الطريقة')},{key:'amount',label:t('Amount','المبلغ'),render:r=><Money value={r.amount}/>}]} />
    </>}{payment&&invoice&&<Modal title={t('Record payment','تسجيل دفعة')} onClose={()=>setPayment(false)}><RecordForm initial={{amount:String(invoice.balance/100),method:'cash'}} fields={[{name:'amount',en:'Amount',ar:'المبلغ',required:true},{name:'method',en:'Payment method',ar:'طريقة الدفع',type:'select',options:methods.map(m=>({value:m,label:m}))},{name:'notes',en:'Notes',ar:'ملاحظات'}]} onSubmit={async v=>{await api('payments.create',{sale_id:saleId,amount:minor(String(v.amount)),method:v.method,notes:v.notes});await client.invalidateQueries();setPayment(false);}}/></Modal>}
    {returnLine&&<Modal title={t('Return item','إرجاع منتج')} onClose={()=>setReturnLine(null)}><RecordForm initial={{quantity:'1',method:'cash',restock:true}} fields={[{name:'quantity',en:'Quantity',ar:'الكمية',type:'number',min:1,required:true},{name:'reason',en:'Reason',ar:'السبب',required:true},{name:'method',en:'Refund method',ar:'طريقة الاسترداد',type:'select',options:methods.map(m=>({value:m,label:m}))},{name:'restock',en:'Return to available stock',ar:'إعادة إلى المخزون المتاح',type:'checkbox'}]} onSubmit={async v=>{await api('returns.create',{sale_id:saleId,reason:v.reason,method:v.method,items:[{sale_item_id:returnLine,quantity:Number(v.quantity),restock:Boolean(v.restock)}]});await client.invalidateQueries();setReturnLine(null);}}/></Modal>}
  </Modal>;
}
